alter table PM_PROJECT_GOAL add constraint FK_PM_PROJECT_GOAL_COMPANY_GOAL foreign key (COMPANY_GOAL_ID) references PM_COMPANY_GOAL(ID);
alter table PM_PROJECT_GOAL add constraint FK_PM_PROJECT_GOAL_PROJECT foreign key (PROJECT_ID) references PM_PROJECT(ID);
create index IDX_PM_PROJECT_GOAL_COMPANY_GOAL on PM_PROJECT_GOAL (COMPANY_GOAL_ID);
create index IDX_PM_PROJECT_GOAL_PROJECT on PM_PROJECT_GOAL (PROJECT_ID);
